language: python
python:
    - "2.7"
install:
    - "python setup.py -q install"
    - "pip install -r requirements-dev.txt"
    - "pip install coverage"
    - "pip install coveralls"
script:
    - "coverage run --source teiler setup.py test"
    - "flake8 teiler"
    #    - "flake8 tests"
after_success:
    coveralls
notifications:
    email: false
