language: python
python:
    - "2.7"
install:
    - "make install-dev"
    - "pip install coveralls"
script:
    - "make cover"
    - "make lint"
after_success:
    coveralls
notifications:
    email: false
