language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=lint

install:
    - pip install tox codecov

script:
    - tox -e $TOX_ENV

after_success:
    - codecov

notifications:
    email: false
