language: python
python:
    - "2.7"
install:
    - "python setup.py -q install"
    - "pip install -r requirements-dev.txt"
    - "pip install coverage"
    - "pip install coveralls"
script:
    - "coverage run --source teiler setup.py test"
after_success:
    coveralls
