language: python
branches:
    only:
        - master 
python:
    - "2.7"
#    - "3.3"
#    - "3.4"
# deps
install: 
    - "python setup.py -q install"
#vscript to run tests
script: 
    - "trial backend/tests" 

