language: python
branches:
    only:
        - dev
python:
    - "2.7"
before-install:
    - "sudo apt-get update && sudo apt-get install swig"
    - "pip install http://dl.dropbox.com/u/174789/m2crypto-0.20.1.tar.gz"
# deps
install: 
    - "pip install -r requirements.txt --use-mirrors"
#vscript to run tests
script: 
    - "python trial src" 

